# Telegram Bot Configuration
telegram:
  bot_token: "YOUR_BOT_TOKEN"
  chat_id: "YOUR_CHAT_ID"

# Product Configuration
products:
  - product_id: "1"  # This is a unique identifier for the product, will be used in the database
    name: "PlayStation 5 Console"
    urls: 
      - "https://www.amazon.com/dp/B08X3W4J7X"
    
  - product_id: "2"  
    name: "iPhone 13 Pro Max"
    urls: 
      - "https://www.ebay.com/itm/254678923456"

# Website Configuration
websites:
  amazon:
    base_url: "https://www.amazon.com.br/dp/"
    currency: "R$"

# Database Configuration
database:
  path: "data/price_history.db"
  type: "sqlite"
  backup_days: 7  # Keep backups for 7 days


logging:
  file: "app.log"

scraping:
  user_agents: 
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
  request_timeout: 15  # in seconds
  headers:
    Accept-Language: "pt-BR,pt;q=0.9"
    Accept-Encoding: "gzip, deflate"
  retry_attempts: 3    # Number of retry attempts for failed requests


# Alert Configuration
alerts:
  price_drop_percentage: 5  # Minimum % drop to trigger alert
  notify_every: 86400       # Max 1 alert per 24 hours per product
  currency_symbol: "$"

# Graph Configuration
graph:
  save_path: "graphs/"
  days_to_show: 30  # Show price history for last X days
  theme: "ggplot"   # matplotlib style
  colors:
    current_price: "#FF0000"
    historical_prices: "#00FF00"